### ISSUE TITLE
TwitchIRC : Null instance when message is send by an user with chat badges

### ISSUE THREAD

**Issue by Fifut** [kanimaru/twitcher#13]
`func prepare_message(message: String, parent: RichTextLabel) -> String:` 
`...`
`   var tex = resource.get_frame_texture("default", 0;` 
`...`

 return null instance when message is send by an user with chat badges

**Comment by Fifut** [comment]
And sometimes `var resource = ResourceLoader.load(path, "SpriteFrames") as SpriteFrames;` too

**Comment by kanimaru** [comment]
are you using the lastest branch or assetlib cause I think this is already fixed on the latest version

**Comment by Fifut** [comment]
I use the assetlib version. I will try the lastest branch.

**Comment by Fifut** [comment]
Unfortunatly, I have the same problem with the last branch version :cry:
I use Godot 4.2.2

**Comment by kanimaru** [comment]
Do you have something to reproduce?

**Comment by Fifut** [comment]
It seems to work now.
I did a clean install of the plugin with the last branch.

Thx
