### ISSUE TITLE
Remove signal twitch_ready

### ISSUE THREAD

**Issue by Fifut** [kanimaru/twitcher#14]
In twitch_service.gd `signal twitch_ready;` no longer exists since commit 506d05c

**Comment by kanimaru** [comment]
Its replaced with `await TwitchService.setup();`

**Comment by Fifut** [comment]
Yes but the signal is still declared.

**Comment by kanimaru** [comment]
https://github.com/kanimaru/twitcher/commit/4f0e3967457541da213e7eb0f3b7b210b92b72be Thanks yeah xD forgot
