### ISSUE TITLE
[Urgent] Secrets getting stored unencrypted in the project settings

### ISSUE THREAD

**Issue by kanimaru** [kanimaru/twitcher#15]
Twitcher needs it's own setting file for the credentials. They getting currently stored unencrypted in the project file that is in the root folder of the project. And people could accidently check this file into their git repo....

**Comment by Goutte** [comment]
As a workaround, our team uses the `override.cfg` file for our secrets, which we exclude from git using the `.gitignore` file.

**Comment by kanimaru** [comment]
Closed in the latest master changes
