### ISSUE TITLE
Channel guest star EventSub: unknow validation error

### ISSUE THREAD

**Issue by lublak** [kanimaru/twitcher#31]
I don't know if it is possible. I don't use the broadcast id in the settings. I just use Twitcher as Client Application "client_id" without client_secrect. So the broadcast id is unkown to me. The user logs in in my application.

```
[TwitchHttpClient-1-https://api.twitch.tv] Start request processing [2] /helix/eventsub/subscriptions?
[TwitchHttpClient-1-https://api.twitch.tv] Problems with /helix/eventsub/subscriptions? result 400 body: 
{"error":"Bad Request","status":400,"message":"unknown validation error: Key: 'SubscriptionCondition.broadcaster_user_id' Error:Field validation for 'broadcaster_user_id' failed on the 'required' tag\nKey: 'SubscriptionCondition.moderator_user_id' Error:Field validation for 'moderator_user_id' failed on the 'required' tag"}[/color]
[TwitchEventSub] Subscription failed for event 'channel.guest_star_session.begin'. Error 400: {"error":"Bad Request","status":400,"message":"unknown validation error: Key: 'SubscriptionCondition.broadcaster_user_id' Error:Field validation for 'broadcaster_user_id' failed on the 'required' tag\nKey: 'SubscriptionCondition.moderator_user_id' Error:Field validation for 'moderator_user_id' failed on the 'required' tag"}
[TwitchHttpClient-1-https://api.twitch.tv] Start request processing [2] /helix/eventsub/subscriptions?
```
![grafik](https://github.com/user-attachments/assets/c78353a4-8fef-447f-8191-829ef1887049)

**Comment by kanimaru** [comment]
Most of them requires Broadcaster ID look at the docs: https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/

**Comment by lublak** [comment]
@kanimaru Can this not be auto obtained via the api? I am logged in with oauth from the user. https://dev.twitch.tv/docs/api/reference/#get-users

**Comment by kanimaru** [comment]
Probably I auto genereated most of them the Eventsub part is the worst of it cause its partially useless in configuration. You still can subscribe the eventsub stuff manually via code for your use case probably the better choose anyway.

**Comment by lublak** [comment]
@kanimaru yes i think its a better solution. i just close it here,
