### ISSUE TITLE
It shouldn't apply login cooldown if first log in?

### ISSUE THREAD

**Issue by artbarte** [kanimaru/twitcher#35]
I think it should apply the cooldown if _last_login_attempt is 0?
https://github.com/kanimaru/twitcher/blob/3ecd25b4799078fd54b1308e5b148fb9c23ddab7/addons/twitcher/lib/oOuch/oauth.gd#L74

Possible solution:
`if _last_login_attempt != 0 && Time.get_ticks_msec() - 60 * 1000 < _last_login_attempt:`

**Comment by kanimaru** [comment]
Fixed in f4d3f25ebbc68d06e15a1764ef5e87d83807d264
