### ISSUE TITLE
example chat breaks if someone posts the same emote twice

### ISSUE THREAD

**Issue by merlinseela** [kanimaru/twitcher#4]
![image](https://github.com/kanimaru/twitcher/assets/101634748/df5c1bfb-ae62-40dd-99dc-59963383ba70)

![image](https://github.com/kanimaru/twitcher/assets/101634748/9dd20f14-d958-49cc-bd2d-3e79fdd9921f)

**Comment by merlinseela** [comment]
the second screenshot was the msg that broke the example.

testes with multiple emotes. sending a singular emote would work without problems though.

**Comment by merlinseela** [comment]
putting text in between the sprites also kill it
![image](https://github.com/kanimaru/twitcher/assets/101634748/f32872eb-2224-4d8b-a748-4907bd9f0ccf)

**Comment by merlinseela** [comment]
found out this breaks it aswell 
![image](https://github.com/kanimaru/twitcher/assets/101634748/0a988faf-92ef-4317-a31f-dba9c6c815af)

**Comment by kanimaru** [comment]
Fixed with [12af59d](https://github.com/kanimaru/twitcher/commit/12af59d204e048f94d32af77e9b7f9ed7463f354).
Problem was that the static image parser made problems aka was not saving the converted spriteframes.
