### ISSUE TITLE
Any ideas why the authentication is failing?

### ISSUE THREAD

**Issue by QuinnQueue** [kanimaru/twitcher#44]
I'm trying to send messages and receive messages from twitch chat for a custom overlay which I plan to do a lot more with later but for now this will do. I've done everything in the chat example scene. My token is up to date:

Here's what the log looks like:
[TwitchService] Setup
[TwitchAuthorization] Connecting to https://id.twitch.tv
[TwitchAuthorization] Start Request(0) /oauth2/.well-known/openid-configuration
[TwitchHttpClient-1-https://api.twitch.tv] connecting to https://api.twitch.tv
[TwitchService] Start
[TwitchHttpClient-1-https://api.twitch.tv] Connection state changed: true
[TwitchAuthorization] Start request processing [0] /oauth2/.well-known/openid-configuration
[TwitchAuthorization] Connecting to https://id.twitch.tv
true
[TwitchWebsocket] Set connection to wss://irc-ws.chat.twitch.tv:443
[TwitchHttpClient-1-https://api.twitch.tv] Start Request(0) /helix/chat/emotes/global?
[TwitchHttpClient-1-https://api.twitch.tv] Start request processing [0] /helix/chat/emotes/global?
[TwitchHttpClient-1-https://api.twitch.tv] Start Request(0) /helix/chat/emotes?broadcaster_id=1054205040&
[TwitchHttpClient-1-https://api.twitch.tv] Start request processing [0] /helix/chat/emotes?broadcaster_id=1054205040&
[TwitchHttpClient-1-https://api.twitch.tv] Start Request(0) /helix/chat/badges/global?
[TwitchHttpClient-1-https://api.twitch.tv] Start request processing [0] /helix/chat/badges/global?
[TwitchHttpClient-1-https://api.twitch.tv] Start Request(0) /helix/chat/badges?broadcaster_id=1054205040&
[TwitchHttpClient-1-https://api.twitch.tv] Start request processing [0] /helix/chat/badges?broadcaster_id=1054205040&
[TwitchWebsocket] Set connection to wss://eventsub.wss.twitch.tv/ws
[TwitchWebsocket] Set connection to ws://127.0.0.1:8081/ws
[TwitchHttpClient-1-https://api.twitch.tv] Start Request(0) /helix/bits/cheermotes?broadcaster_id=1054205040&
[TwitchService] Initialized and ready
[TwitchHttpClient-1-https://api.twitch.tv] Start request processing [0] /helix/bits/cheermotes?broadcaster_id=1054205040&
[TwitchWebsocket] Connecting to wss://irc-ws.chat.twitch.tv:443
[TwitchWebsocket] connected to wss://irc-ws.chat.twitch.tv:443
[TwitchIRC] < NICK QueueStudioQuinn
[TwitchIRC] < CAP REQ :twitch.tv/commands
[TwitchIRC] < JOIN #queuestudioquinn
[TwitchIRC] > [         NOTICE] tmi.twitch.tv: Login unsuccessful
[TwitchIRC] Authentication failed.
[TwitchIRC] Can't connect
[TwitchIRC] > [            CAP] tmi.twitch.tv: twitch.tv/commands
[TwitchIRC] < JOIN #queuestudioquinn

Here's what my general project settings look like:
![settings](https://github.com/user-attachments/assets/48dc23be-49cc-4dfd-884a-01f52ba94d2f)

Here's my twitcher project settings look like:
![token valid](https://github.com/user-attachments/assets/36774b24-734c-4961-85b4-5f227a4c8483)

Here's what I've already tried:
- I tried messing with my firewall
- All of the different authorization settings in general
- Messing with my IRC name and channel name in the settings

Here's what I haven't tried:
- Turning shields down on the brave browser
- Trying other browsers

**Comment by kanimaru** [comment]
Hi that seems to be a hard problem. 
I would exclude network based issues cause you got a connection to IRC. 
Browser shouldn't be a problem either, you got redirected to the login page / authorization of the scopes?
Looks similar to that:
![image](https://github.com/user-attachments/assets/4a842be2-e5fd-44ce-99fb-344eb328a076)

second thing that could be a problem. Under wich account did you created the application? Do you have an explicit bot account? Cause twitch doesn't allow Bot accounts without mod permissions to read chat of other persons anymore.

Another option you could look into Twitch has a new eventsub that also receives chat messsages.
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatmessage
In my opinion even the better solution cause it does alot of parsing for you. When I wrote the lib it wasn't there, so the example still uses the IRC one.

**Comment by QuinnQueue** [comment]
Nope! Never seen a page like this before. Here's the page it directs me to before it breaks.

![Screenshot (29)](https://github.com/user-attachments/assets/6e7dd677-433c-4577-b3de-ddf9713ad383)

then i get a problem loading page error.

**Comment by QuinnQueue** [comment]
FIXED!
I used http intsead of https
