### ISSUE TITLE
Possibility to make Twitcher less verbose in godot's output

### ISSUE THREAD

**Issue by couscousyeah** [kanimaru/twitcher#45]
First thanks a lot for this addon !

I tried to find a convenient way to toggle twitcher in a less verbose/not verbose at all way because it ran in the way of other informations I needed in the output, and only found a (bad) way by commenting the last line in `twitch_logger_manager.gd` : 

`logger.set_enabled(TwitchSetting.is_log_enabled(logger.context_name));`

Is there an option I missed or is it possible to make it an option to get rid of outpu messages when needed ?

**Comment by kanimaru** [comment]
![grafik](https://github.com/user-attachments/assets/03d5eee9-bb46-480f-b0f7-c0fc1a0eb32d)
Isn't the settings to control what kind of logging you want be enough?

**Comment by couscousyeah** [comment]
Ok i'm feeling so stupid right now, i've looked at that so many times (but too fast) that I didnt realise it was the loggers options... 

thanks  !
