### ISSUE TITLE
Making a button to remove cached items

### ISSUE THREAD

**Issue by kanimaru** [kanimaru/twitcher#9]
Remove Cached items like

- Badges
- Emotes
- Auth

Maybe as Toolbar Item like Regenerate Rest button?

**Comment by lublak** [comment]
@kanimaru a generell feature for "logout" would be usefull. So someone can switch accounts.

**Comment by kanimaru** [comment]
Added buttons for clearing cache and token in f9b3aa20ee3906218009fed1f018b8f25ec5121b
